[package]
name = "MIT"
version = "0.2.0"
edition = "2021"

[features]
enable_backpropagation = [] # 역전파 관련 기능들을 활성화 할경우 사용
requires_grad = [] # 기울기의 중간 저장이 필요할 경우 사용

[dependencies]

[profile.dev]
debug = true

[profile.release]
opt-level = 3