[package]
name = "trench-deep"
version = "0.0.2"
edition = "2024"
description = "This framework is a project that I am independently designing/developing to study about deep learning. Basic levels of computation and automatic differential engines are implemented."
readme = "README.md"
repository = "https://github.com/3QNRpDwD/TrenchDeep"
license = "Apache 2.0 License"
keywords = ["DL", "ML", "AI", "deep-learning", "machine-learning"] # 검색에 도움이 될 키워드
authors = ["2QRNpDwD@gmail.com"]
categories = ["science", "algorithms", "data-structures", "mathematics"]

[features]
enableBackpropagation = [] # 역전파 관련 기능들을 활성화 할경우 사용
enableHigherOrderDifferentiation = ["requiresGrad"] # 고계 미분 관련 기능들을 활성화 할경우 사용 (enableBackpropagation 필요)
enableVisualization = ["enableBackpropagation"] # 시각화 기능을 활성화 할경우 사용 (enableBackpropagation 필요)
requiresGrad = ["enableBackpropagation"] # 기울기의 중간 저장이 필요할 경우 사용 (enableBackpropagation 필요)
debugging = [] # 디버깅이 필요할 경우 사용

[dependencies]
rand = "0.9.1"                      #테스트시 초깃값 생성용 랜덤 크레이트
log = "0.4.27"                      #테스트시 로깅용 크레이트
tracing-subscriber = { version = "0.3", features = ["fmt", "registry", "env-filter", "time"] } # 위와 동일
tracing-appender = "0.2.3"          # 위와 동일
mnist = "0.6.0"                     # 테스트시 입력할 데이터셋 크레이트
serde = { version = "1.0.219", features = ["derive"] } #테스트시 모델 저장용 크레이트
serde_json = "1.0.140"                                 #테스트시 모델 저장용 크레이트
indicatif = "0.17.11"             #테스트시 로깅용 크레이트
tracing = "0.1.41"                 #테스트시 로깅용 크레이트
time = { version = "0.3.41", features = ["macros"] }
thiserror = "2.0.12"               #오류 전파용 크레이트

[profile.dev]
debug = true

[profile.release]
debug = true
opt-level = 3

#This framework is a project that I am independently designing/developing to study about deep learning.
#If you have any better ideas for the project, please contact us here at 2QRNpDwD@gmail.com or https://github.com/3QNRpDwD.

