// Read-only repository analysis. Writes only project-data.js in this tool folder.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const here=path.dirname(fileURLToPath(import.meta.url));
const repo=path.resolve(here,'../..');
const model=createRequire(import.meta.url)('./model.js');
const slash=p=>p.split(path.sep).join('/');
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const inventory=[];
function walk(dir){
  for(const item of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){
    if(['.git','target','node_modules','.sites-runtime','.idea','.codex','.agents','tools'].includes(item.name))continue;
    const absolute=path.join(dir,item.name);
    if(item.isDirectory())walk(absolute);
    else if(item.isFile())inventory.push({path:slash(path.relative(repo,absolute)),bytes:fs.statSync(absolute).size});
  }
}
walk(repo);
const sources={},warnings=[];
for(const graph of model.graphs)for(const node of graph.nodes)for(const ref of [...node.sources,...(node.legacy?.sources||[])]){
  const key=ref.path+'#'+(ref.anchor||'');
  if(sources[key])continue;
  const raw=fs.readFileSync(path.join(repo,ref.path),'utf8');
  const lines=raw.split(/\r?\n/);
  const index=ref.anchor?lines.findIndex(line=>line.includes(ref.anchor)):0;
  if(index<0)warnings.push(key);
  const begin=Math.max(0,index-2);
  sources[key]={path:ref.path,line:Math.max(1,index+1),start:begin+1,verified:index>=0,hash:hash(raw),code:lines.slice(begin,begin+24).join('\n')};
}
// Module declarations are facts, not a whole-program Rust name resolver.
const modules=[];
for(const file of inventory.filter(f=>f.path.endsWith('.rs'))){
  const lines=fs.readFileSync(path.join(repo,file.path),'utf8').split(/\r?\n/);
  lines.forEach((line,index)=>{
    if(/^\s*(pub(?:\([^)]*\))?\s+)?mod\s+\w+\s*[;{]/.test(line)||/^\s*pub use\s/.test(line))modules.push({path:file.path,line:index+1,declaration:line.trim(),context:lines.slice(Math.max(0,index-3),index).filter(l=>l.trim().startsWith('#['))});
  });
  file.preview=lines.slice(0,65).join('\n');
}
const cargo=fs.readFileSync(path.join(repo,'Cargo.toml'),'utf8');
const data={schemaVersion:1,generatedAt:new Date().toISOString(),fingerprint:hash(cargo+Object.values(sources).map(s=>s.hash).join('')),inventory,sources,modules,cargo,warnings};
fs.writeFileSync(path.join(here,'project-data.js'),'// Generated by build.mjs; repository inputs are read only.\nglobalThis.PROJECT_DATA = '+JSON.stringify(data).replace(/</g,'\\u003c')+';\n');
console.log(`${inventory.length} files, ${Object.keys(sources).length} source references, ${modules.length} module declarations`);
if(warnings.length){console.error('Unresolved source anchors:\n'+warnings.join('\n'));process.exitCode=1;}
